// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GetAvailableMonths():Promise<Array<string>>;

export function GetOverallTotal():Promise<domain.TokenUsage>;

export function GetSummaryForMonth(arg1:string):Promise<domain.MonthSummary>;

export function ScanLogs():Promise<void>;
