// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableMonths() {
  return window['go']['ui']['WailsAdapter']['GetAvailableMonths']();
}

export function GetOverallTotal() {
  return window['go']['ui']['WailsAdapter']['GetOverallTotal']();
}

export function GetSummaryForMonth(arg1) {
  return window['go']['ui']['WailsAdapter']['GetSummaryForMonth'](arg1);
}

export function ScanLogs() {
  return window['go']['ui']['WailsAdapter']['ScanLogs']();
}
